//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorGet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailableTime
    {
        public int Id { get; set; }
        public System.DateTime Available { get; set; }
        public int TutorId { get; set; }
    
        public virtual Tutor Tutor { get; set; }
    }
}
