//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorGet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Booking
    {
        public int Id { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yy HH:mm}", ApplyFormatInEditMode = true)]
        [DataType(DataType.DateTime)]
        [Required]
        [Display(Name = "Lesson Time")]
        public string DateTime { get; set; }
        [Required]
        public string UserId { get; set; }
        [Required]
        [Display(Name ="Tutor")]
        public int TutorId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Tutor Tutor { get; set; }
    }
}
